### ISSUE TITLE
ValueError in generating synthetic records with `forge()`

### ISSUE THREAD

**Issue by robsdavis** [bips-hb/arfpy#2]
### The issue
When I run `forge(n=num_new_records)` sometimes it works, but sometimes it throws a value error (`ValueError: Domain error in arguments. The `scale` parameter must be positive for all distributions, and many distributions have restrictions on shape parameters. Please see the `scipy.stats.truncnorm` documentation for details.`). The problem seems to be more frequent as I increase `num_new_records`.

### Minimal example
```
from sklearn.datasets import load_diabetes
from arfpy import arf
import pandas as pd

# Load data
diabetes = load_diabetes() 
df = pd.DataFrame(diabetes['data'], columns=diabetes['feature_names'])

# Train the ARF
my_arf = arf.arf(x = df)

# Get density estimates
my_arf.forde()

# Generate data
my_arf.forge(n = 100)
```
output:
```
Initial accuracy is 0.755656108597285
Iteration number 1 reached accuracy of 0.41968325791855204.
0.0
0.0920990148468528
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[19], line 16
     13 my_arf.forde()
     15 # Generate data
---> 16 my_arf.forge(n = 100)

File [~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/arfpy/arf.py:351](https://file+.vscode-resource.vscode-cdn.net/home/rob/Documents/projects/synthcity/tutorials/plugins/generic/~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/arfpy/arf.py:351), in arf.forge(self, n)
    349  myloc = obs_params.loc[obs_params["variable"] == colname, "mean"]
    350  myscale = obs_params.loc[obs_params["variable"] == colname, "sd"]
--> 351  data_new.loc[:, j] = scipy.stats.truncnorm(a =(myclip_a - myloc) [/](https://file+.vscode-resource.vscode-cdn.net/) myscale,b = (myclip_b - myloc) [/](https://file+.vscode-resource.vscode-cdn.net/) myscale, loc = myloc , scale = myscale ).rvs(size = n)
    352  del(myclip_a,myclip_b,myloc,myscale)
    353 else:

File [~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:468](https://file+.vscode-resource.vscode-cdn.net/home/rob/Documents/projects/synthcity/tutorials/plugins/generic/~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:468), in rv_frozen.rvs(self, size, random_state)
    466 kwds = self.kwds.copy()
    467 kwds.update({'size': size, 'random_state': random_state})
--> 468 return self.dist.rvs(*self.args, **kwds)

File [~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:1036](https://file+.vscode-resource.vscode-cdn.net/home/rob/Documents/projects/synthcity/tutorials/plugins/generic/~/miniconda3/envs/synthcity-all/lib/python3.9/site-packages/scipy/stats/_distn_infrastructure.py:1036), in rv_generic.rvs(self, *args, **kwds)
   1030 if not np.all(cond):
   1031     message = ("Domain error in arguments. The `scale` parameter must "
   1032                "be positive for all distributions, and many "
   1033                "distributions have restrictions on shape parameters. "
   1034                f"Please see the `scipy.stats.{self.name}` "
   1035                "documentation for details.")
-> 1036     raise ValueError(message)
   1038 if np.all(scale == 0):
   1039     return loc*ones(size, 'd')

ValueError: Domain error in arguments. The `scale` parameter must be positive for all distributions, and many distributions have restrictions on shape parameters. Please see the `scipy.stats.truncnorm` documentation for details.
```

**Comment by kristinblesch** [comment]
Thank you for reporting this! The issue stems from terminal nodes in the fitted `arf`  where a continuous variable has a standard deviation of zero. When such a terminal node is sampled for data synthesis with `forge`, the error is triggered. 

In your specific case, all features are passed as floats even though there are features in the dataset that have only two distinct values. Hence, it is quite likely that there will be some terminal nodes where only one of the two distinct values of that feature is present, i.e., we get terminal nodes with zero standard deviation features. I highly recommend passing such features as type object/category and not float. 

It might still occur that continuous variables have a zero standard deviation within terminal nodes though, for example, if you’re heavily overfitting the training data. In such cases you might want to consider increasing `min_node_size`. For cases where this does not help (or is not desired for some other reason), I updated the development version of the code here on GitHub such that in case of zero standard deviations, the feature value that is present in the terminal node will be used for the generated sample as well. We will work on more flexible solutions for this in the future and may incorporate these changes when releasing an updated version of `arfpy` on pypi.
